import os
import sqlite3

import psycopg2


def get_db():
    db_url = os.getenv("DATABASE_URL")
    conn = psycopg2.connect(db_url)
    return conn

def init_db():
    conn = get_db()
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS counts (
              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name TEXT UNIQUE NOT NULL,
              value INTEGER NOT NULL DEFAULT 0
        )
   """)
    cursor.execute(""" 
            INSERT INTO COUNTS (name, value)
            VALUES (%s, %s), (%s, %s)
            ON CONFLICT (NAME) DO NOTHING;
        """, ("phone", 0, "direct", 0)) 
    
    conn.commit()
    cur.close()
    conn.close()

